import { LoaderIcon } from './icons';
import cn from 'classnames';

interface ImageEditorProps {
  title: string;
  content: string;
  isCurrentVersion: boolean;
  currentVersionIndex: number;
  status: string;
  isInline: boolean;
  metadata?: {
    provider?: string;
    model?: string;
  };
}

export function ImageEditor({
  title,
  content,
  status,
  isInline,
  metadata,
}: ImageEditorProps) {
  // Extract provider info from metadata or title
  const providerFromMetadata = metadata?.provider;
  const providerFromTitle = title?.match(/generated by ([\w\s]+)\)/i)?.[1];
  const providerInfo = providerFromMetadata || providerFromTitle;

  return (
    <div
      className={cn(
        'flex flex-row items-center justify-center w-full relative',
        {
          'h-[calc(100dvh-60px)]': !isInline,
          'h-[200px]': isInline,
        },
      )}
    >
      {status === 'streaming' ? (
        <div className="flex flex-row gap-4 items-center">
          {!isInline && (
            <div className="animate-spin">
              <LoaderIcon />
            </div>
          )}
          <div>Generating Image...</div>
        </div>
      ) : (
        <div className="relative">
          <picture>
            <img
              className={cn('w-full h-fit max-w-[800px]', {
                'p-0 md:p-20': !isInline,
              })}
              src={`data:image/png;base64,${content}`}
              alt={title}
            />
          </picture>

          {providerInfo && (
            <div className="absolute top-2 right-2 bg-black/75 text-white text-xs font-medium px-2 py-1 rounded-md shadow-sm z-10 backdrop-blur-sm">
              {providerInfo}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
